baseURL: "https://roszcz.github.io"
languageCode: "en-us"
title: "Cooking Show for Python Developers"
theme: "toha-labs"

# Control TOC depth
#markup:
#  tableOfContents:
#    startLevel: 2
#    endLevel: 6
#    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home: 
  - HTML
  - RSS
  - JSON

# Enable global emoji support
enableEmoji: true

params:
  # enableBlogPost: true
  enableTOC: true

  author:
    name: "tomek"
    image: "/images/douple-p.gif"
    blogname: "quasiscientific garbage"

  socialLinks:   
    - name: "Email"
      url: "roszcz+blog@gmail.com"
      icon: "fas fa-envelope"
    
    - name: "twitter"
      url: "https://twitter.com/roszczt"
      icon: "fab fa-twitter"

  newsletter:
    enable: false

  customMenus:
    - name: Posts
      url: /posts

    - name: About
      url: /pages/about

  footer:
      enable: true
      # You can provide your custom footer template using this option.
      # Put your template in "layouts/partials" folder of your repo.
      template: footer.html
      # Show/hide navigation in the footer. Default is "true".
      navigation:
        enable: false
      # Show/hide "Contact Me" section in the footer. Default is "true".
      contactMe:
        enable: false
      # Show/hide credentials section in the footer. Default is "true".
      credentials:
        enable: true

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: monokai
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
